import type { Metadata } from "next";
import { Manrope, Quicksand, Twinkle_Star } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const twinkleStar = Twinkle_Star({
  variable: "--font-twinkle-star",
  subsets: ["latin"],
  weight: ["400"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} ${quicksand.variable} ${twinkleStar.variable} antialiased bg-[rgb(31,31,31)] w-screen min-h-screen grid grid-cols-1 lg:grid-cols-[260px_1fr]`}
      >
        <Navbar />
        <main className="overflow-auto">{children}</main>
      </body>
    </html>
  );
}
